@baseUrl=https://localhost:7111
@apiKey=sk_HxtRNQ1ZgyGBpNuAAKeJpIvQ4SOUlvNL.McgrHuElDC

### List registered anchors
GET {{baseUrl}}/api/anchors
Content-Type: application/json
X-Api-Key: {{apiKey}}

### Register a new anchor
# Provide the DigitalLink anchor, the company prefix and the description of the product/anchor
POST {{baseUrl}}/api/anchors
Content-Type: application/json
X-Api-Key: {{apiKey}}
{
  "prefix": "01/05414195535264",
  "description": "Product description"
}

### Get details of an anchor
GET {{baseUrl}}/api/anchors/qTFrufVwob
Content-Type: application/json
X-Api-Key: {{apiKey}}

### Register a link for a specific anchor
POST {{baseUrl}}/api/anchors/qTFrufVwob/links
Content-Type: application/json
X-Api-Key: {{apiKey}}
{
  "linkType": "gs1:pip",
  "redirectUrl": "https://en.test.com/2",
  "title": "product info",
  "languages": [ "en-001" ],
  "mediaType": "text/html",
  "isDefault": true
}

### Remove a link from an anchor
DELETE {{baseUrl}}/api/anchors/qTFrufVwob/links/HpSATmuEMA
Content-Type: application/json
X-Api-Key: {{apiKey}}