@baseUrl=https://localhost:7111

### Resolves the entire list of links for the specified DigitalLink
GET {{baseUrl}}/01/05414196535263
Accept-Language: fr-BE
Accept: application/linkset+json

### Resolves a linkType for the specified DigitalLink
GET {{baseUrl}}/01/05414196535263?linkType=gs1:defaultLink
Accept: */*

### Time-Travel - Send a request for a specific DateTime
# This feature is useful to replay a request and/or performing validations on the configured links (for example promotion or time-specific resolutions)
# The X-Request-Date header specifies the date and time of the request. This must be in ISO 8601 format, and must be in the past.
GET {{baseUrl}}/01/05414196535263?linkType=gs1:homepage
Accept-Language: fr-BE
Accept: */*

### No Tracking - Bypass insights tracking for the request
# This request will not appear in the /api/insights results. It will not be tracked at all
# Used when debugging a request or when validating the configuration
# The X-Request-Tracking header with a value of 'bypass' or 'notrack' will not be tracked
GET {{baseUrl}}/01/05414195535264?linkType=gs1:consumerHandlingStorageInfo
Accept-Language: fr-BE
Accept: */*
X-Request-Tracking: bypass

### CORS
OPTIONS {{baseUrl}}/01/05414195535264
Origin: https://foo.example
Access-Control-Request-Method: GET, HEAD, OPTIONS

### HEAD
HEAD {{baseUrl}}/01/05414195535264
Accept: */*
X-Request-Tracking: bypass

### Get the metadata of the resolver
GET {{baseUrl}}/.well-known/gs1resolver