@Gs1DigitalLink.Api_HostAddress = https://localhost:7113

## Decompress a GS1 DigitalLink
POST {{Gs1DigitalLink.Api_HostAddress}}/api/decompress
Accept: application/json
Content-Type: application/json
{
  "DigitalLink": "CwnZLmc7QAw8SA"
}

###
## Compress a GS1 DigitalLink
## CompressionType can be set to Full or Partial
POST {{Gs1DigitalLink.Api_HostAddress}}/api/compress
Accept: application/json
Content-Type: application/json
{
  "DigitalLink": "01/05414195535264/10/123456",
  "CompressionType": "Full", 
  "CompressQueryString": false
}

###
## Register a link type
POST {{Gs1DigitalLink.Api_HostAddress}}/api/register
Accept: application/json
X-Company-Prefix: 952012
Content-Type: application/json
{
  "Prefix": "/01/09520123456887",
  "RedirectUrl": "https://example.com/product{/gtin}?lang=en",
  "Title": "Example redirection",
  "Language": "en-GB",
  "LinkTypes": ["gs1:pip"]
}

###
## Resolve a DigitalLink
GET {{Gs1DigitalLink.Api_HostAddress}}/01/09520123456887?linkType=gs1:pip
Accept: application/json