@Gs1DigitalLink.Web_HostAddress = https://localhost:7113

###
## Register a link type
POST {{Gs1DigitalLink.Web_HostAddress}}/api/register
Accept: application/json
X-Company-Prefix: 952012
Content-Type: application/json
{
  "Prefix": "/01/09520123456887",
  "RedirectUrl": "https://example.com/product{/gtin}?lang=en",
  "Title": "Example redirection",
  "Language": "en-GB",
  "LinkTypes": ["gs1:pip"]
}

###
## Resolve a DigitalLink
GET {{Gs1DigitalLink.Web_HostAddress}}/01/09520123456887?linkType=gs1:pip
Accept: application/json